### ISSUE TITLE
function filter_one_country() returns wrong results for China, France etc.

### ISSUE THREAD

**Issue by andre-schneider-fraunhofer** [Priesemann-Group/covid19_inference_forecast#3]
First of all: Thank you very much for your commitment and for the release of the covid19_inference_forecast source code via Github. Good job indeed!

In the past few days I have also read in and processed data from Johns Hopkins University for my own analyzes. I noticed the following problem: There are (at least) three constellations concerning the columns 'Province/State' and 'Country/Region':

(1) empty/null cell for 'Province/State', a single row for the 'Country/Region' (e.g. Germany)
(2) multiple rows for one Country/Region (e.g. China) with all entries for 'Province/State' (inside the main country
(3) same as (2) above + an additional row for the main country (e.g. France) with an empty/null cell for 'Province/State', here the other rows (with names for 'Province/State') contain external territories.

That means your function filter_one_country() needs some further improvements:

(A) looking for country with empty/null content in the 'Province/State' column
    (this should work for countries like Germany (1) and France (3)
(B) filter all rows for the selected country and calculate the sum of all numbers (cases, deaths, ...)

The following code works for me (only as a suggestion - I'm a Python/Pandas newbie):

`

        y = d[(d['Province/State'].isnull()) & (d['Country/Region']==country)]

        if len(y)==1:

            y = y.values[0][x0:]

        elif len(y)==0:

            y = d[d['Country/Region']==country].sum().values[x0:]

        else:

            print('ERROR: country = ' + country)
`

Happy Easter!
André

(Computational Analytics Group @ Fraunhofer IIS Dresden)

**Comment by jdehning** [comment]
Thanks, it is implemented now and committed. When you test it make sure that you are using version 0.0.7 of the module. I tested it for China, Germany and France.
